### ISSUE TITLE
Initial UI project structure.

### ISSUE THREAD

**Issue by yoX64** [e-spres-oh/sherlock-ui#1]
Install whatever framework you want.

**Comment by fulf** [comment]
Will go for [Angular.io](https://angular.io/) and follow their quick start guide at first. Then I'll see how I can integrate [webpack](https://webpack.js.org/) with it and if it would actually make any sense.

**Comment by horiaradu** [comment]
You don’t have to integrate it. It’s already there. If u want, we can have
a quick chat and i can give you an overview and some good resources

**Comment by horiaradu** [comment]
Here u go: https://www.udemy.com/the-complete-guide-to-angular-2/learn/v4/
